# Generated by Django 5.2.7 on 2025-11-22 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_seed_roomtypes_and_rooms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=126.0, help_text='The total cost to the customer for this reservation.', max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_city',
            field=models.CharField(blank=True, help_text="City of the customer's address.", max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_country',
            field=models.CharField(blank=True, help_text="Country of the customer's primary address.", max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_state',
            field=models.CharField(blank=True, help_text="State or province of the customer's address.", max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_street',
            field=models.CharField(blank=True, help_text='Street address of the customer.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_zipcode',
            field=models.CharField(blank=True, help_text='ZIP or postal code for the customer.', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary contact phone number for the customer.', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(help_text='Link this customer to a Django user account.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the reservation was first created.'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Optional link to a registered customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.customer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(help_text='Check-out date for the reservation.'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiration_time',
            field=models.DateTimeField(blank=True, help_text='Optional expiration time for holds or temporary reservations.', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_email',
            field=models.CharField(help_text='Email address of the guest.', max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_first_name',
            field=models.CharField(help_text='First name of the guest making the reservation.', max_length=35),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_last_name',
            field=models.CharField(help_text='Last name of the guest making the reservation.', max_length=35),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(help_text='Phone number of the guest for contact purposes.', max_length=25),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Specific room assigned to this reservation, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.ForeignKey(blank=True, help_text='Optional preference for a specific room type.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.roomtype'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(help_text='Check-in date for the reservation.'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Hold', 'Hold'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Hold', help_text='Current status of the reservation.', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Automatically updated timestamp when the reservation is modified.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='maintenance_until',
            field=models.DateField(blank=True, help_text='If in maintenance, the date the room is expected to become available.', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(help_text='Unique identifier for the room (e.g., 101, 202).', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(help_text='The type of this room (links to RoomType).', on_delete=django.db.models.deletion.PROTECT, to='web.roomtype'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance')], default='Available', help_text='Current status of the room.', max_length=12),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Automatically updated timestamp when the room record is modified.'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='beds',
            field=models.IntegerField(help_text='Number of beds in this room type.'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or special features of this room type.', null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='max_guests',
            field=models.IntegerField(help_text='Maximum number of guests allowed in this room type.'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(help_text='Name of the room type (e.g., Queen, King, Double Full).', max_length=25),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, help_text='Standard price per night for this room type.', max_digits=7),
        ),
    ]
