# Generated by Django 5.2.7 on 2025-11-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_reservation_total_cost_and_add_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of guests for this reservation.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(help_text='Name of the room type (e.g., Queen, King, Double Full).', max_length=25, unique=True),
        ),
    ]
