# Generated by Django 5.2.7 on 2025-11-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_reservation_guests_alter_roomtype_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='public_id',
            field=models.CharField(
                blank=True, 
                null=True,
                editable=True, 
                help_text='Public-facing reservation ID.', 
                max_length=12, 
                unique=True
            ),
        ),
    ]
